version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=dynamodb,sns,sqs
      - DEFAULT_REGION=eu-west-1
      - EXTERNAL_HOSTNAME=localstack

  faceit:
    image: faceit
    ports:
      - "3000:3000"
    depends_on:
      - localstack